services:

  proxy:
    build:
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
    - echo_service
    ports:
    - "${PORT_PROXY:-10000}:10000"

  echo_service:
    build:
      context: ../shared/echo
    hostname: service1
