filter_chains:
  filters:
    name: "http"
    typed_config: [type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager]:
        codec_type: HTTP2
        stat_prefix: "config_test"
        route_config:
          name: "route_config_0"
          virtual_hosts:
            name: "integration"
            domains: "*"
            routes:
              match:
                prefix: "/"
              route:
                cluster: "cluster_0"
        http_filters:
          name: "envoy.filters.http.gcp_authn"
          typed_config: [type.googleapis.com/net.envoy.source.extensions.filters.http.metadata.GcpAuthnFilterConfig]:
              http_uri:
                uri: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=[AUDIENCE]"
                cluster: "gcp_authn"
                timeout:
                  seconds: 10
        http_filters:
          name: "envoy.filters.http.router"
        access_log:
          name: "accesslog"
          filter:
            not_health_check_filter:
          typed_config:
            [type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog]:
              path: "/dev/null"
        delayed_close_timeout:
          nanos: 100