language: minimal
sudo: required

services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y awscli
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  # TODO(mattklein123): Travis is too slow to continue doing release tests. We are very
  # close to the time limit. Revert this when we get off Travis. We are getting OK 
  # coverage from other test runs.
  - TEST_TYPE=bazel.release.server_only
  - TEST_TYPE=bazel.asan
  - TEST_TYPE=bazel.tsan
  - TEST_TYPE=bazel.coverage
  - TEST_TYPE=check_format
  - TEST_TYPE=docs
  - TEST_TYPE=build_image
script: ./ci/ci_steps.sh

branches:
  only:
    - master
