language: shell
sudo: required
dist: trusty
group: deprecated-2017Q4

services:
  - docker
before_install:
  - ip addr show
  - ls /proc/net
  - cat /proc/net/if_inet6
  - sudo apt-get -qq update
  - sudo apt-get install -y awscli
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=bazel.ipv6_tests
script: ./ci/ci_steps.sh

branches:
  only:
    - master
