language: shell
sudo: required
dist: trusty

services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y awscli
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=bazel.ipv6_tests
before_script:
  # TODO(zuercher): remove this workaround for https://github.com/travis-ci/travis-ci/issues/8891
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script: ./ci/ci_steps.sh

branches:
  only:
    - master
