sudo: required

services:
  - docker

install: true

env:
  - TEST_TYPE=normal
  - TEST_TYPE=coverage
  - TEST_TYPE=asan
  - TEST_TYPE=docs

script: docker run -t -i -v $TRAVIS_BUILD_DIR:/source lyft/envoy-build:latest /bin/bash -c "cd /source && ci/do_ci.sh $TEST_TYPE"
