language: cpp
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=debug
  - TEST_TYPE=normal
  - TEST_TYPE=coverage
  - TEST_TYPE=asan
  - TEST_TYPE=docs
# the before script decrypts the ssh key used to push updates to the gh-pages branch
before_script: openssl aes-256-cbc -K $encrypted_b1a4cc52fa4a_key -iv $encrypted_b1a4cc52fa4a_iv -in .publishdocskey.enc -out .publishdocskey -d
script: ./ci/ci_steps.sh
