language: cpp
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=docs
before_script:
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile .publishdocskey\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_b1a4cc52fa4a_key -iv $encrypted_b1a4cc52fa4a_iv -in .publishdocskey.enc -out .publishdocskey -d
script: ./ci/ci_steps.sh
