{
  "admin": {
    "access_log_path": "/dev/null",
    "address": {
      "socket_address": {
        "address": "0.0.0.0",
        "port_value": 8001
      }
    }
  },
  "layered_runtime": {
    "layers": [
      {
        "name": "static-runtime",
        "static_layer": {
          "re2.max_program_size.error_level": 1000
        }
      }
    ]
  },
  "stats_config": {
    "stats_matcher": {
      "inclusion_list": {
        "patterns": [
          {
            "safe_regex": {
              "google_re2": {},
              "regex": "cluster.(metadata-cluster|iam-cluster|service-control-cluster|backend-cluster-sample-backend-s3fctubhaq-uc.a.run.app_443).upstream_rq_(reset|timeout|[1-5]xx)"
            }
          }
        ]
      }
    }
  }
}
