version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      - envoymesh
    ports:
      - "1999:1999"
      - "8001:8001"

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis_server
    ports:
      - "6379:6379"

networks:
  envoymesh: {}
