version: "3.8"
services:

  kafka-client:
    build:
      context: .
      dockerfile: Dockerfile-kafka
    restart: "no"
    deploy:
      replicas: 0

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
      kafka-server:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN:-8001}:8001"

  kafka-server:
    build:
      context: .
      dockerfile: Dockerfile-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:10000"]
      interval: 5s
      timeout: 60s
      retries: 120
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listener value needs to be equal to cluster value in Envoy config
      # (will receive payloads from Envoy).
      KAFKA_LISTENER: PLAINTEXT://kafka-server:9092
      # Advertised listener value needs to be equal to Envoy's listener
      # (will make clients discovering this broker talk to it through Envoy).
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:10000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile-zookeeper
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -nz 127.0.0.1 2181"]
      interval: 5s
      timeout: 60s
      retries: 120
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
