version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
    - image: envoyproxy/envoy-build-ubuntu:0a02a76af5951bf7f4c7029c0ea6d29d96c0f682
    # TODO(mattklein123): Get xlarge class enabled
    resource_class: medium
    working_directory: /source

jobs:
  docs:
    executor: ubuntu-build
    steps:
    - checkout
    - run: mobile/docs/build.sh
    - add_ssh_keys:
        fingerprints:
        - "33:78:4d:5c:bd:62:2e:43:9d:79:2c:3e:dc:45:c0:98"
    - run: mobile/docs/publish.sh
    - store_artifacts:
        path: generated/docs

workflows:
  version: 2
  all:
    jobs:
    - docs:
        filters:
          tags:
            only: /^v.*/
