version: "3.8"
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    restart: "no"
    deploy:
      replicas: 0

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    ports:
    - target: 10000
      published: ${PORT_PROXY_HTTP3:-10000}
      protocol: udp
      mode: host
    - target: 10000
      published: ${PORT_PROXY_HTTP3:-10000}
      protocol: tcp
      mode: host
    - target: 10001
      published: ${PORT_PROXY_HTTP:-10001}
      protocol: tcp
      mode: host
    - "${PORT_ADMIN:-8001}:8001"
