version: "3.7"

services:
  wasm_compile_update:
    image: envoyproxy/envoy-build-ubuntu:a4bc794b2b87e01cff1c5fe9f9a118b64b0759ce
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_updated_example.wasm && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
    - ../..:/source
    - ./lib:/build

  wasm_compile:
    image: envoyproxy/envoy-build-ubuntu:a4bc794b2b87e01cff1c5fe9f9a118b64b0759ce
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_example.wasm && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
    - ../..:/source
    - ./lib:/build
