version: "3.8"

services:
  wasm_compile_update:
    image: envoyproxy/envoy-build-ubuntu:dafbde9825f965460288eb8aa1326187a9fee5e5
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_updated_example.wasm && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
    - ../..:/source
    - ./lib:/build

  wasm_compile:
    image: envoyproxy/envoy-build-ubuntu:dafbde9825f965460288eb8aa1326187a9fee5e5
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_example.wasm && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
    - ../..:/source
    - ./lib:/build
