version: "3.8"
services:

  #client:

  envoy-hello:
    build:
      context: .
      dockerfile: Dockerfile-envoy-hello
    ports:
    - "${PORT_PROXY:-10000}:8080"
    - 9090:9090

  hello:
    build:
      context: .
      dockerfile: Dockerfile-hello
    command: ["/bin/server", "-world-addr=envoy-world:8080"]

  envoy-world:
    build:
      context: .
      dockerfile: Dockerfile-envoy-world
    ports:
    - "${PORT_PROXY:-10000}:8080"
    - 9090:9090

  world:
    build:
      context: .
      dockerfile: Dockerfile-world
    command: ["/bin/server"]
