version: "3.8"

services:
  stubs_go:
    build:
      context: .
      dockerfile: Dockerfile-grpc-go
    command: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative hello.proto world.proto
    volumes:
    - ./protos:/protos
