version: "3.7"
services:

  flask:
    build:
      context: ../../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
    - "8000:8000"

  frontend-service:
    image: flask:python-3.10-slim-bullseye
    volumes:
    - ./service.py:/code/service.py
    - ./index.html:/code/index.html
