version: "3.7"
services:

  proxy-ws:
    build:
      context: .
      dockerfile: Dockerfile-proxy-ws
    ports:
      - "10000:10000"

  service-ws:
    image: solsson/websocat
    hostname: service-ws
    command: --text -E ws-listen:0.0.0.0:8080 literalreply:boom

  service-wss:
    image: solsson/websocat
    hostname: service-wss
    command: wss-listen:0.0.0.0:8080 literalreply:boom --pkcs12-der /certs/output.pkcs12
    volumes:
      - ./certs/output.pkcs12:/certs/output.pkcs12
