{% macro listener(protocol, address, port_value) -%}
  name: not_requrired_for_static_listeners
  address:
    socket_address:
      protocol: {{protocol}}      
      address: {{address}}
      port_value: {{port_value}}
  filter_chain:
  #tls context is also matched in the filter chain
    filters:
      name: envoy.http_connection_manager
      config:
        codec_type: AUTO
        stat_prefix: router
        router_config: 
  #getting data from router template 
        http_filters:
          - name: envoy.health_check
            config:

          - name: envoy.buffer
            config:
              max_request_bytes: 5242880
              max_request_time: 120

          - name: envoy.rate_limit
            config:
              domain: envoy_front
              request_type: external

          - name: envoy.router
            config: {}            
    use_proxy_proto:
{% endmacro -%}
admin:
  access_log_path: /var/log/envoy/admin_access.log
  socket_address:
    protocol: TCP
    address: 0.0.0.0
    port_value: 9901
flags_path: /etc/envoy/flags
stats_sinks:
  - name: envoy.statsd
    config: 
      tcp_cluster_name: statsd
tracing:
  http:
    name: envoy.lightstep
    config:
      collector_cluster: lightstep_saas
      access_token_file: /etc/envoy/lightstep_access_token
runtime:
  symlink_root: /srv/runtime_data/current
  subdirectory: envoy
  override_subdirectory: envoy_override
rate_limit_service:
  grpc_service:
    envoy_grpc:
      cluster_name: ratelimit
cluster_manager:
  outlier_detection:
    event_log_path: /var/log/envoy/outlier_events.log
static_resources:
  clusters:
    - name: sds
      type: STRICT_DNS
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      hosts:
        - socket_address:
           protocol: TCP           
           address: disccovery.yourcompany.net
           port_value: 80
    - name: statsd
      type: STATIC
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      hosts:
       - socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 8125
    - name: lightstep_saas
      type: LOGICAL_DNS
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      hosts:
       - socket_address:
          protocol: TCP
          address: collector-grpc.lightstep.com
          port_value: 443
  listeners:
    - {{ listener("TCP", "0.0.0.0", "9300")|indent(4) }}
    - {{ listener("TCP", "0.0.0.0", "9301")|indent(4) }}
    - {{ listener("TCP", "0.0.0.0", "9400")|indent(4) }}