{% import 'routing_helper_v2.template.yaml' as helper with context -%}
name: local_route
virtual_hosts:
- name: www
  domains:
  - www.yourcompany.com
  routes:
  - match:
      prefix: "/foo/bar"
      runtime:
        default_value: 0
        runtime_key: routing.www.use_service_2
    route:
      {{ helper.make_route('main_website')|indent(4) }}
  - match:
      prefix: "/"
    route:
      {{ helper.make_route('main_website')|indent(4) }}
  rate_limits:
    actions:
      remote_address: {}
- name: www_redirect
  domains:
  - wwww.yourcompany.net
  routes:
  - match:
      prefix: "/"
    redirect:
      host_redirect: www.yourcompany.net
  rate_limits:
  - actions:
      remote_address: {}
- name: api
  domains:
  - api.yourcompany.net
  routes:
  - match:
      path: "/foo/bar"
    route:
      {{ helper.make_route('main_website')|indent(4) }}
  - match:
      prefix: "/"
    route:
      {{ helper.make_route('main_website')|indent(4) }}
  rate_limits:
  - actions:
      remote_address: {}