{% import 'routing_helper_v2.template.yaml' as helper -%}
{% macro router_file_content() -%}{% include kwargs['router_file'] -%}{% endmacro -%}
{% macro listener(protocol, address, port_value, proxy_proto) -%}
  name: not_requrired_for_static_listeners
  address:
    socket_address:
      protocol: {{protocol}}
      address: {{address}}
      port_value: {{port_value}}
  filter_chains:
  - tls_context:
      common_tls_context:
        alpn_protocols: h2,http/1.1
        tls_certificates:
          certificate_chain:
            filename: certs/servercert.pem
          private_key:
            filename: certs/serverkey.pem
    filters:
    - name: envoy.http_connection_manager
      config:
        codec_type: AUTO
        stat_prefix: router
        {% if proxy_proto -%}
        use_remote_address: true
        {%endif-%}
        stat_prefix: ingress_http
        route_config:
          name: local_route
          virtual_hosts:
          - name: www
            domains:
            - www.yourcompany.com
            routes:
            - match:
                prefix: "/foo/bar"
              route:
                cluster: main_website
            rate_limits:
              actions:
                remote_address: {}
        http_filters:
        - name: envoy.router
          config: {}
          name: envoy.health_check
          config:
            pass_through_mode: false
            endpoint: "/healthcheck"
          name: envoy.buffer
          config:
            max_request_bytes: 5242880
            max_request_time: 120
          name: envoy.rate_limit
          config:
            domain: envoy_front
            request_type: external
          name: envoy.router
          config: {}
{% endmacro -%}
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - {{ listener("TCP", "0.0.0.0", "9300", True)|indent(2) }}
  - {{ listener("TCP", "0.0.0.0", "9301", True)|indent(2) }}
  - {{ listener("TCP", "0.0.0.0", "9400", True)|indent(2) }}
  clusters:
  - name: sds
    type: STRICT_DNS
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
       protocol: TCP
       address: disccovery.yourcompany.net
       port_value: 80
  - name: statsd
    type: STATIC
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 8125
  - name: lightstep_saas
    type: LOGICAL_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: collector-grpc.lightstep.com
        port_value: 443
  - name: main_website
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: main_website.com
        protocol: TCP
        port_value: 443
cluster_manager:
  outlier_detection:
    event_log_path: /var/log/envoy/outlier_events.log
flags_path: /etc/envoy/flags
runtime:
  symlink_root: /srv/runtime_data/current
  subdirectory: envoy
  override_subdirectory: envoy_override