{%- macro listener(protocol, address, port_value, proxy_proto) -%}
- name: listener_created_from_configgen
  address:
    socket_address:
      protocol: {{protocol}}
      address: {{address}}
      port_value: {{port_value}}
  filter_chains:
  - filter_chain_match:
      sni_domains: example.com
    tls_context:
      common_tls_context:
        alpn_protocols: h2,http/1.1
        tls_certificates:
          certificate_chain:
            filename: certs/servercert.pem
          private_key:
            filename: certs/serverkey.pem
    filters:
    - name: envoy.http_connection_manager
      config:
        codec_type: AUTO
        stat_prefix: router
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains: ["*"]
            routes:
            - match:
                prefix: "/"
              route:
                host_rewrite: www.google.com
                cluster: backhaul
        http_filters:
        - name: envoy.health_check
          config:
            pass_through_mode: false
            endpoint: /healthcheck
          name: envoy.buffer
          config:
            max_request_bytes: 5242880
            max_request_time: 120
          name: envoy.router
          config: {}
        access_log:
          name: envoy.file_access_log
          config:
            path: /etc/envoy/file_access_log
        {% if proxy_proto %}
        use_remote_address: true
        {%endif -%}
   {% if proxy_proto %}
    use_proxy_proto: true
   {%endif -%}
{% endmacro -%}
static_resources:
  listeners:
  {{ listener("TCP", "0.0.0.0",9300,True)|indent(2) }}
  {{ listener("TCP", "0.0.0.0",9301,True)|indent(2) }}
  clusters:
  - name: statsd
    type: STATIC
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 8125
  - name: backhaul
    type: STRICT_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: front-proxy.yourcompany.net
        port_value: 9400
    max_requests_per_connection: 25000
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain:
            filename: certs/clientcert.pem
          private_key:
            filename: certs/clientkey.pem
        validation_context:
          verify_subject_alt_name:
            - front-proxy.yourcompany.net
  - name: lightstep_saas
    type: LOGICAL_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: collector-grpc.lightstep.com
        port_value: 443
    #adding some http2 protocol options for tracing to work
    http2_protocol_options:
      max_concurrent_streams: 1000000
    tls_context:
      common_tls_context:
        validation_context:
          trusted_ca:
            filename: certs/cacert.pem
          verify_subject_alt_name:
          - collector-grpc.lightstep.com
flags_path: /etc/envoy/flags
stats_sinks:
  name: envoy.statsd
  config: 
    tcp_cluster_name: statsd
tracing:
  http:
    name: envoy.lightstep
    config:
      access_token_file: etc/envoy/lightstep_access_token
      collector_cluster: lightstep_saas
runtime:
  symlink_root: /srv/runtime_data/current
  subdirectory: envoy
  override_subdirectory: envoy_override
admin:
  access_log_path: "var/log/envoy/admin_access.log"
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901