{% import 'routing_helper_v2.template.yaml' as helper -%}
{% import 'access_log_format_helper_v2.template.yaml' as access_log_helper -%}
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.main_website.com
                  cluster: main_website
          http_filters:
          - name: envoy.router
            config: {}



  - name: listener_1
    address:
      socket_address:
        protocol: TCP
        port_value: 9002
        address: 127.0.0.1
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: AUTO
          stat_prefix: egress_http
          #change route_config to RDS
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.main_website.com
                  cluster: main_website
          add_user_agent: true
          tracing:
            operation_name: EGRESS
          idle_timeout: 840s
          #change this filter to an or_filter with status_code>=400 or duration_filter>=2000
          access_log:
          - name: envoy.file_access_log
            filter:
              not_health_check_filter:
                {}
            config:
              path: "/var/log/envoy/egress_http_error.log"
          use_remote_address: true
          http_filters:
          - name: envoy.rate_limit
            config:
              domain: envoy_service_to_service
          - name: envoy.grpc_http1_bridge
            config: {}
          - name: envoy.router
            config: {}


  clusters:
  {% for mapping in external_virtual_hosts -%}
  {% for host in mapping['hosts'] -%}
  - name: egress_{{ host['name'] }}
    #need to update tls and timeout accordingly
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: {{ host['remote_address'] }}
        port_value: {{ host['port_value'] }}
        protocol: {{ host['protocol'] }}
  {% endfor -%}
  {% endfor -%}
  {% for key, value in mongos_servers.iteritems() -%}
  - name: mongo_{{ key }}
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: RANDOM
    hosts:
    {% for server in value['hosts'] -%}
    - socket_address:
        protocol: {{ server['protocol'] }}
        port_value: {{ server['port_value'] }}
        address: {{ server['address'] }}
    {% if not loop.last -%}{% endif -%}
    {% endfor -%}
  {% endfor %}
  - name: main_website
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: main_website.com
        port_value: 443
    tls_context: { sni: www.main_website.com }
  - name: local_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 8080
    circuit_breakers:
      thresholds:
        max_pending_requests: 30
        max_connections: 100
  - name: local_service_grpc
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    #adding some http2 option, need to be rechecked
    http2_protocol_options:
      max_concurrent_streams: 100
    hosts:
    - socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 8081
    circuit_breakers:
      thresholds:
        max_requests: 200
  - name: rds
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: rds.yourcompany.net
        port_value: 80
  - name: statsd
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 8125
  - name: lightstep_saas
    connect_timeout: 1s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN    
    hosts:
    - socket_address:
        protocol: TCP
        address: collector-grpc.lightstep.com
        port_value: 443
    http2_protocol_options:
      max_concurrent_streams: 100
    tls_context:
      common_tls_context:
        validation_context:
          trusted_ca:
            filename: certs/cacert.pem
          verify_subject_alt_name:
          - collector-grpc.lightstep.com            
  - name: cds_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS  
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        protocol: TCP
        address: cds.yourcompany.net
        port_value: 80
flags_path: /etc/envoy/flags
stats_sinks:
  - name: envoy.statsd
    config:
      tcp_cluster_name: statsd
tracing:
  http:
    name: envoy.lightstep
    config:
      access_token_file: /etc/envoy/lightstep_access_token
      collector_cluster: lightstep_saas
rate_limit_service:
  grpc_service:
    envoy_grpc:
      #cluster_name needs to be changed      
      cluster_name: main_website
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901


