version: "3.7"
services:

  flask:
    build:
      context: ../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
    - "8080:8080"
    - "8443:8443"
    - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    - ./service.py:/code/service.py
    environment:
    - SERVICE_NAME=1

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    - ./service.py:/code/service.py
    environment:
    - SERVICE_NAME=2
