version: '2'
services:

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.json:/etc/service-envoy.json
      - ./key.pem:/etc/key.pem
      - ./cert.pem:/etc/cert.pem
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
      - "9400"

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.json:/etc/service-envoy.json
      - ./key.pem:/etc/key.pem
      - ./cert.pem:/etc/cert.pem
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
      - "9400"

networks:
  envoymesh: {}
