version: "3.7"
services:

  # base images
  flask:
    build:
      context: ../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  tracing:
    build:
      context: ../shared/tracing
    image: envoyproxy:tracing
    restart: "no"

  # jaeger
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
    - "8000:8000"
    dns:
    - 8.8.8.8
    - 8.8.4.4

  service1:
    image: envoyproxy:tracing
    volumes:
    - ./service1-envoy-jaeger.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=1
    dns:
    - 8.8.8.8
    - 8.8.4.4

  service2:
    image: envoyproxy:tracing
    volumes:
    - ./service2-envoy-jaeger.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=2
    dns:
    - 8.8.8.8
    - 8.8.4.4

  jaeger:
    image: jaegertracing/all-in-one
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
    - "16686:16686"
