resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: v1
    type: STRICT_DNS
    load_assignment:
      cluster_name: v1
      endpoints:
        - lb_endpoints:
          - endpoint:
            address:
              socket_address:
                address: 10.130.10.89
                port_value: 8888
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: v2
    type: STRICT_DNS
    load_assignment:
      cluster_name: v2
      endpoints:
        - lb_endpoints:
            - endpoint:
              address:
                socket_address:
                  address: 10.130.10.89
                  port_value: 8889
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: v3
    type: STRICT_DNS
    load_assignment:
      cluster_name: v3
      endpoints:
        - lb_endpoints:
            - endpoint:
              address:
                socket_address:
                  address: 10.130.10.89
                  port_value: 8890