version: "3.7"
services:
  envoy-stats:
    build:
      context: .
      dockerfile: Dockerfile-gzip
    networks:
      - envoymesh
    ports:
      - "10000:10000"
      - "10001:10001"
      - "8089:8089"

  service:
    build:
      context: .
      dockerfile: Dockerfile-service
    networks:
      - envoymesh

networks:
  envoymesh: {}
