services:

  proxy:
    build:
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
      helloworld_service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"
    environment:
    # The Envoy Golang filter is designed to be run with the GODEBUG=cgocheck=0
    # environment variable set.
    # This disables the cgo pointer check.
    # Failure to set this environment variable will cause Envoy to crash!
    - GODEBUG=cgocheck=0

  helloworld_service:
    build:
      context: ../shared/python
      target: aiohttp-hello-service
