version: '2'
services:

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - ./config/s2s-python-envoy.yml:/etc/s2s-python-envoy.yml
    expose:
      - "9001"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    volumes:
      - ./config/s2s-grpc-envoy.yml:/etc/s2s-grpc-envoy.yml
    expose:
      - "9211"
