version: "3.7"

services:

  # Requires the build of the stubs first
  grpc-server:
    image: envoyproxy/example-kv-server
    build:
      context: server
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      envoymesh:
        aliases:
          - kv-backend-service

  grpc-server-proxy:
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c /etc/server-envoy-proxy.yaml --service-cluster backend-proxy
    volumes:
      - ./server/envoy-proxy.yaml:/etc/server-envoy-proxy.yaml
    networks:
      envoymesh:
        aliases:
          - kv-backend-proxy
    expose:
      - "8811"
      - "8881"
    ports:
      - "8811:8811"
      - "8881:8881"

networks:
  envoymesh: {}
