parameters:
- name: ciTarget
  displayName: "CI target"
  type: string
  default: bazel.release
- name: artifactSuffix
  displayName: "Suffix of artifact"
  type: string
  default: ""
- name: rbe
  displayName: "Enable RBE"
  type: boolean
  default: true
- name: managedAgent
  type: boolean
  default: true
- name: bazelBuildExtraOptions
  type: string
  default: "--flaky_test_attempts=2"

steps:
- task: Cache@2
  displayName: Cache ("${{ parameters.ciTarget }}")
  inputs:
    key: '"${{ parameters.ciTarget }}" | ./WORKSPACE | **/*.bzl'
    path: $(Build.StagingDirectory)/repository_cache
  continueOnError: true

- script: .azure-pipelines/docker-cache.sh mount_ephemeral /tmp/ephemeral
  displayName: Create ephemeral cache import directory
  condition: ${{ parameters.managedAgent }}
- task: Cache@2
  displayName: "Docker cache (${{ parameters.ciTarget }})"
  inputs:
    key: "envoy-build-ubuntu | 0_0_0 | .devcontainer/Dockerfile"
    path: /tmp/ephemeral/docker
    cacheHitVar: CACHE_RESTORED
  continueOnError: true
  condition: ${{ parameters.managedAgent }}
- script: .azure-pipelines/docker-cache.sh restore /tmp/ephemeral/docker/cache.tar.gz
  displayName: "Docker cache restore (${{ parameters.ciTarget }})"
  continueOnError: true
  condition: and(${{ parameters.managedAgent }}, not(canceled()), eq(variables.CACHE_RESTORED, 'true'))

- bash: |
    echo "disk space at beginning of build:"
    df -h
  displayName: "Check disk space at beginning"

- script: ci/run_envoy_docker.sh 'ci/do_ci.sh ${{ parameters.ciTarget }}'
  workingDirectory: $(Build.SourcesDirectory)
  env:
    ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
    SLACK_TOKEN: $(SLACK_TOKEN)
    REPO_URI: $(Build.Repository.Uri)
    BUILD_URI: $(Build.BuildUri)
    ${{ if parameters.rbe }}:
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
      ENVOY_RBE: "1"
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-ci --jobs=$(RbeJobs) ${{ parameters.bazelBuildExtraOptions }}"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
    ${{ if eq(parameters.rbe, false) }}:
      BAZEL_BUILD_EXTRA_OPTIONS: "${{ parameters.bazelBuildExtraOptions }}"
      BAZEL_REMOTE_CACHE: $(LocalBuildCache)

  displayName: "Run CI script ${{ parameters.ciTarget }}"

- bash: |
    echo "disk space at end of build:"
    df -h
    # Cleanup offending files with unicode names
    rm -rf $(Build.StagingDirectory)/tmp/*/*/external/go_sdk/test/fixedbugs
  displayName: "Check disk space at end"
  condition: always()

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/bazel-out/**/testlogs/**/test.xml"
    testRunTitle: "${{ parameters.ciTarget }}"
    searchFolder: $(Build.StagingDirectory)/tmp
  timeoutInMinutes: 10
  condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "$(Build.StagingDirectory)/envoy"
    artifactName: ${{ parameters.ciTarget }}${{ parameters.artifactSuffix }}
  timeoutInMinutes: 10
  condition: always()
