resources:
  containers:
  - container: envoy-build
    image: envoyproxy/envoy-build:d0cefa7f071dbd4ef24399c2db8656c3a5d8c3ef

jobs:
- job: BuildEnvoy
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  container: envoy-build
  steps:
  - script: bazel build //source/exe:envoy-static

