resources:
  containers:
  - container: envoy-build
    image: envoyproxy/envoy-build:07f65995ece0b8a21bb2888d07a8c1d060e7daaa

jobs:
- job: BuildEnvoy
  pool:
    vmImage: 'Ubuntu 16.04'
  container: envoy-build
  steps:
  - script: bazel build -c opt //source/... --action_env=PATH=PATH=/usr/lib/llvm-8/bin:$PATH --action_env=CC=clang --action_env=CXX=clang++

