resources:
  containers:
  - container: envoy-build
    image: envoyproxy/envoy-build:8246167b9d238797cbc6c03dccc9e3921c37617d

jobs:
- job: EnvoyFullTest
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  container: envoy-build
  steps:
  - script: ci/do_ci.sh bazel.release
    env:
      ENVOY_SRCDIR: $(Build.SourcesDirectory)
      BUILD_DIR: $(Build.StagingDirectory)
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-clang --config=remote-ci --jobs=100 --curses=no"
      BAZEL_EXTRA_TEST_OPTIONS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/envoy"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/testlogs/**/test.xml'
      testRunTitle: 'bazel.release'
      searchFolder: $(Build.StagingDirectory)
      mergeTestResults: true
      publishRunAttachments: true
    condition: always()
