jobs:
- job: BuildAndTest
  strategy:
    matrix:
      Release:
        CI_TARGET: 'bazel.release'
      ASAN:
        CI_TARGET: 'bazel.asan'
      TSAN:
        CI_TARGET: 'bazel.tsan'
  dependsOn: [] # this removes the implicit dependency on previous stage and causes this to run in parallel.
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: |
      echo "disk space at beginning of build:"
      df -h

  - bash: |
      cd $(Build.SourcesDirectory)
      ci/run_envoy_docker.sh 'ci/do_ci.sh $(CI_TARGET)'
    env:
      ENVOY_SRCDIR: $(Build.SourcesDirectory)
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-clang --config=remote-ci --jobs=100 --curses=no"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)

  - bash: |
      echo "disk space at end of build:"
      df -h
    condition: always()

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/envoy"
      artifactName: 'envoy'
