resources:
  containers:
  - container: envoy-build
    image: envoyproxy/envoy-build:8246167b9d238797cbc6c03dccc9e3921c37617d

jobs:
- job: EnvoyFullTest
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  container: envoy-build
  steps:
  - script: ci/do_ci.sh bazel.asan
    env:
      ENVOY_SRCDIR: $(Build.SourcesDirectory)
      BUILD_DIR: $(Build.StagingDirectory)
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-clang --experimental_inmemory_jdeps_files --experimental_inmemory_dotd_files --experimental_remote_download_outputs=minimal --jobs=100 --curses=no"
      BAZEL_EXTRA_TEST_OPTIONS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only"
      BAZEL_REMOTE_CACHE: remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/testlogs/**/test.xml'
      testRunTitle: 'bazel.asan'
      searchFolder: $(Build.StagingDirectory)
    condition: always()
