# Azure Pipelines
# TODO(lizan): Consider rolling all presubmit jobs into one file.
trigger:
- master

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: |
        .\ci\windows_ci_setup.ps1
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR"
      displayName: "Install dependencies"
      env:
        TOOLS_BIN_DIR: $(Pipeline.Workspace)\bin

    - bash: |
        set -ex
        mkdir -p /c/tmp
        touch /c/tmp/created
        ls -lah /c && ls -lah /c/tmp
        # demonstrate rm not working
        rm -rf /tmp
        cd / && /c/windows/system32/cmd.exe "/d /c cd && dir"
        ls -lah / && ls -lah /tmp
        # demonstrate cmd.exe rmdir not working
        cd / && /c/windows/system32/cmd.exe "/d /c rmdir /s /q tmp"
        ls -lah / && ls -lah /tmp
        # symlink /tmp to /c/tmp
        /c/windows/system32/cmd.exe "/d /c mklink /d tmp C:\\tmp && cd && dir /n"
        ls -lah / && ls -lah /tmp && ls -lah /c/tmp
      displayName: "Resolve bash /tmp to c:\\tmp"

    - bash: ci/windows_ci_steps.sh
      displayName: "Run Windows CI"

