# Azure Pipelines
# TODO(lizan): Consider rolling all presubmit jobs into one file.
trigger:
- master

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: |
        .\ci\windows_ci_setup.ps1
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR\bin;$env:TOOLS_BIN_DIR\usr\bin"
        Write-Host "##vso[task.prependpath]$env:VC_TOOLS_BIN_X64;$env:VC_CMAKE_PATH\CMake\bin;$env:VC_CMAKE_PATH\Ninja"
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR"
      displayName: "Install dependencies"
      env:
        TOOLS_BIN_DIR: $(Pipeline.Workspace)\bin
        VC_CMAKE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake"
        VC_TOOLS_BIN_X64: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VCTools\\MSVC\\14.24.28314\\bin\\HostX64\\x64"

    - bash: ci/windows_ci_steps.sh
      displayName: "Run Windows CI"
      env:
        BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC"
        BAZEL_SH: $(Pipeline.Workspace)/bin/bin/bash.exe
        MSYS2_ARG_CONV_EXCL: "*"
        TMPDIR: $(Agent.TempDirectory)
