# Azure Pipelines
# TODO(lizan): Consider rolling all presubmit jobs into one file.
trigger:
- master

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: |
        .\ci\windows_ci_setup.ps1
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR"
      displayName: "Install dependencies"
      env:
        TOOLS_BIN_DIR: $(Pipeline.Workspace)\bin

    - bash: |
        set -ex
        mkdir -p /c/tmp
        cd / && cmd.exe "/c rmdir /s /q tmp"
        ls -lah /tmp
        ls -lah /c/tmp
        cmd.exe "/c mklink /d tmp C:\\tmp"
        ls -lah /tmp
        ls -lah /c/tmp
      displayName: "Resolve bash /tmp to c:\\tmp"

    - bash: ci/windows_ci_steps.sh
      displayName: "Run Windows CI"

