name: cc_tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  cctests:
    name: cc_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:0a02a76af5951bf7f4c7029c0ea6d29d96c0f682
    steps:
    - uses: actions/checkout@v1
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: 'Run tests'
      run: |
        cd mobile && ./bazelw test \
            --action_env=LD_LIBRARY_PATH \
            --test_output=all \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/cc/...
