name: Check for latest_release of deps

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          bazel run //tools/dependency:check -- -c release_issues
          bazel run //tools/dependency:check -- -c cves -w error
