name: core

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittests:
    name: unit_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./mobile/ci/mac_ci_setup.sh
      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazel test \
            --test_output=all \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //mobile/test/common/...
