name: Publish & verify

on:
  check_run:
    types:
    - completed

concurrency:
  group: |
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' &&  github.event.check_run.conclusion == 'success' && github.event.check_run.name == 'envoy-setec (Environment Repository)' }}
    uses: ./.github/workflows/_env.yml
    with:
      check_mobile_run: false
      prime_build_image: true
      is_pr: ${{ toJson(github.event.check_run.pull_requests) != '[]' && true || false }}
      repo_sha: ${{ github.event.check_run.head_sha }}
      repo_ref: >-
        ${{ toJson(github.event.check_run.pull_requests) != '[]'
            && format('refs/pull/{0}/merge', github.event.check_run.pull_requests[0].number)
            || github.event.check_run.head_sha }}
      start_check_status: >-
        ${{ toJson(github.event.check_run.pull_requests) != '[]'
            && 'Verify/examples'
            || '' }}
      repo_ref: ${{ inputs.ref }}

    permissions:
      contents: read
      statuses: write

  publish:
    needs:
    - env
    uses: ./.github/workflows/_stage_publish.yml
    name: Publish ${{ needs.env.outputs.repo_ref_title }}
    with:
      build_image_ubuntu: ${{ needs.env.outputs.build_image_ubuntu }}
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      version_dev: ${{ needs.env.outputs.version_dev }}
      given_ref: ${{ inputs.ref }}
      repo_ref: ${{ needs.env.outputs.trusted != 'true' && inputs.ref || '' }}
    permissions:
      contents: write

  verify:
    uses: ./.github/workflows/_stage_verify.yml
    name: Verify ${{ needs.env.outputs.repo_ref_title }}
    needs:
    - env
    with:
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      given_ref: ${{ inputs.ref }}
      repo_ref: ${{ needs.env.outputs.trusted != 'true' && needs.env.outputs.repo_ref || '' }}
