name: Envoy/release

permissions:
  contents: read

on:
  release:
    types:
    - published
    branches:
    - main
    - release/v*
  workflow_dispatch:
    inputs:
      task:
        description: Select a task
        required: true
        default: create-release
        type: choice
        options:
          - create-release
      # only 1.25 does not have its own CI
      # remove this and assoc logic when 1.25 goes EOL
      target-branch:
        description: Target branch
        default: default
        type: choice
        options:
        - default
        - release/v1.25
      pr:
        type: boolean
        default: true
      pr_author:
        description: >-
          User/email, eg 'Myname <me@mymail.com'
          (only used to create-release, defaults last commiter to `changelogs/summary.md`)
      pr_message:
        description: Additional message for PR, eg to fix an issue or additional signoff (optional)

jobs:
  ## Triggerable actions

  # Create a release commit, when landed this will publish.
  create_release:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' && inputs.task == 'create-release'
    name: Create release
    steps:
    - id: checkout
      name: Checkout Envoy repository
      uses: envoyproxy/toolshed/gh-actions/github/checkout@actions-v0.0.27
      with:
        app_id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
        app_key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}
        config: |
          ref: ${{ inputs.target-branch == 'release/v1.25' && 'release/v1.25' || '' }}
    - run: |
        if [[ ! -s "changelogs/summary.md" ]]; then
            echo "Changelog summary (`changelogs/summary.md`) is empty!"
            exit 1
        fi
      name: Check changelog summary
    - run: |
        if [[ "$TARGET_BRANCH" == "release/v1.25" ]]; then
            BRANCHNAME="v1.25"
        else
            BRANCHNAME="${GITHUB_REF_NAME#release/}"
        fi
        echo "name=${BRANCHNAME}" >> $GITHUB_OUTPUT
        echo "full_name=release/create/${BRANCHNAME}" >> $GITHUB_OUTPUT
      name: Get branch name
      id: branch
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
    - if: ${{ inputs.pr_author }}
      name: Validate signoff email
      uses: envoyproxy/toolshed/gh-actions/email/validate@actions-v0.0.27
      with:
        email: ${{ inputs.pr_author }}
    - run: |
        git config --global user.name $COMMITTER_NAME
        git config --global user.email $COMMITTER_EMAIL
      name: Configure committer
      env:
        COMMITTER_NAME: publish-envoy[bot]
        COMMITTER_EMAIL: 140627008+publish-envoy[bot]@users.noreply.github.com
    - run: |
        BAZEL_ARGS=(-- -l debug -v debug)
        BAZEL_RUN_ARGS=()
        CHANGELOG_COMMITTER="$(git log -n 1 --format="%an <%ae>" -- changelogs/summary.md)"
        if [[ -n "$PR_AUTHOR" ]]; then
            BAZEL_ARGS+=(
                --release-author="${PR_AUTHOR}"
                --release-signoff="${CHANGELOG_COMMITTER}")
        else
            BAZEL_ARGS+=(--release-author="${CHANGELOG_COMMITTER}")
        fi
        if [[ "${{ inputs.target-branch }}" != "release/v1.25" ]]; then
            BAZEL_RUN_ARGS+=(--config=ci)
        fi
        bazel run "${BAZEL_RUN_ARGS[@]}" @envoy_repo//:release "${BAZEL_ARGS[@]}"
        VERSION=$(cat VERSION.txt)
        echo "version=v${VERSION}" >> $GITHUB_OUTPUT
      name: Create release
      id: release
      env:
        PR_AUTHOR: ${{ inputs.pr_author }}

    - uses: envoyproxy/toolshed/gh-actions/upload/diff@actions-v0.0.27
      name: Upload diff
      with:
        name: release-${{ steps.branch.outputs.name }}
        diff: HEAD^1
        show: true
    - name: Create a PR
      if: ${{ inputs.pr }}
      uses: envoyproxy/toolshed/gh-actions/github/pr@actions-v0.0.27
      with:
        base: ${{ inputs.target-branch != 'default' && inputs.target-branch || github.ref_name }}
        commit: false
        append-commit-message: true
        body: Created by Envoy dependency bot for @${{ github.actor }}
        branch: ${{ steps.branch.outputs.full_name }}
        title: '[release/${{ steps.branch.outputs.name }}] repo: Release ${{ steps.release.outputs.version }}'
        GITHUB_TOKEN: ${{ steps.checkout.outputs.token }}

  ## Triggered actions

  # On release to `main`:
  # - fork the branch to a release branch
  # - add an initial dev commit
  # - remove anything unwanted
  # - push branch
  create_release_branch:
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && endsWith(github.ref, '.0')
    name: Create release branch
    steps:
    - name: Fetch token for app auth
      id: appauth
      uses: envoyproxy/toolshed/gh-actions/appauth@actions-v0.0.27
      with:
        app_id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
        key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ steps.appauth.outputs.token }}
    - name: Create release branch
      run: |
        version="$(cut -d- -f1 < VERSION.txt | cut -d. -f-2)"
        release_branch="release/v${version}"
        commit_sha="$(git rev-parse HEAD)"
        git config --global user.name "$COMMITTER_NAME"
        git config --global user.email "$COMMITTER_EMAIL"
        echo "Creating ${release_branch} from ${commit_sha}"
        git checkout -b "$release_branch"
        bazel run @envoy_repo//:dev -- --patch
        git rm -rf .github/workflows/mobile*yml
        git commit . -m "repo: Remove mobile ci for release branch"
        git log
        git push origin "$release_branch"
      env:
        COMMITTER_NAME: publish-envoy[bot]
        COMMITTER_EMAIL: 140627008+publish-envoy[bot]@users.noreply.github.com
