name: ios_tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  swifttests:
    name: swift_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v1
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Start simulator'
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: ./mobile/ci/start_ios_simulator.sh
    - name: 'Run swift library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --experimental_ui_max_stdouterr_bytes=10485760 \
            --test_output=streamed \
            --config=ios \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/swift:test
  objctests:
    name: c_and_objc_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v1
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Objective-C library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=streamed \
            --config=ios \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/objective-c/...  \
            //test/cc/unit:envoy_config_test
