name: mobile_traffic_director

on:
  # TODO(abeyad): remove all except the cron schedule once I've debugged.
  push:
    branches:
    - main
  pull_request:
  schedule:
  # Once a day at midnight.
  - cron: '0 0 * * *'

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  cc_test:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    name: cc_test
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run GcpTrafficDirectorIntegrationTest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCP_SERVICE_ACCOUNT_JWT_TOKEN: ${{ secrets.GCP_SERVICE_ACCOUNT_JWT_TOKEN }}
        # TODO(abeyad): rm this after debugging
        SONATYPE_PROFILE_ID: ${{ secrets.EM_SONATYPE_PROFILE_ID }}
      run: |
        cd mobile && ./bazelw test \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            --config=ci \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            --test_env="SONATYPE_PROFILE_ID=$SONATYPE_PROFILE_ID" \
            --test_env="GCP_JWT_PRIVATE_KEY=$GCP_SERVICE_ACCOUNT_JWT_TOKEN" \
            //test/non_hermetic:gcp_traffic_director_integration_test --test_output=all
