name: android_tests

permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    uses: ./.github/workflows/_env.yml
    with:
      prime_build_image: true
    permissions:
      contents: read

  android_test:
    name: ${{ matrix.target }}
    needs: env
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
        # Only kotlin tests are executed since with linux:
        # https://github.com/envoyproxy/envoy-mobile/issues/1418.
        - target: kotlin_tests_linux
          name: Run Kotlin library integration tests
          diskspace_hack: true
          timeout-minutes: 90
          runs-on: ${{ needs.env.outputs.agent_ubuntu }}
          env: |
            CC: /opt/llvm/bin/clang
            CXX: /opt/llvm/bin/clang++
          command: |
            ./bazelw test \
                --build_tests_only \
                --config=test-android \
                --config=mobile-remote-ci \
                --define=signal_trace=disabled \
                //test/kotlin/...
        - target: java_tests_linux
          name: Run Java library tests
          timeout-minutes: 120
          runs-on: ${{ needs.env.outputs.agent_ubuntu }}
          run: |
            ./bazelw test \
                --build_tests_only \
                --config=test-android \
                --config=mobile-remote-ci \
                --define=signal_trace=disabled \
                //test/java/...
    uses: ./.github/workflows/_mobile_ci.yml
    with:
      target: ${{ matrix.target }}
      name: ${{ matrix.name }}
      env: ${{ matrix.env }}
      command: ${{ matrix.command }}
      build_image: ${{ needs.env.outputs.build_image_ubuntu_mobile }}
      diskspace_hack: ${{ matrix.diskspace_hack == 'true' }}
      runs-on: ${{ matrix.runs-on }}
      timeout-minutes: ${{ fromJSON(matrix.timeout-minutes) }}
      skip: ${{ needs.env.outputs.mobile_android_tests != 'true' }}
