name: android_tests

permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    uses: ./.github/workflows/_env.yml
    permissions:
      contents: read
      statuses: write

  javatestslinux:
    if: ${{ needs.env.outputs.mobile_android_tests == 'true' }}
    needs: env
    permissions:
      contents: read
      packages: read
    name: java_tests_linux
    runs-on: ${{ needs.env.outputs.agent_ubuntu }}
    timeout-minutes: 90
    container:
      image: ${{ needs.env.outputs.build_image_ubuntu_mobile }}
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v4
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run Java library integration tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile
        ./bazelw test \
            --build_tests_only \
            --config=test-android \
            --config=mobile-remote-ci \
            --define=signal_trace=disabled \
            //test/java/...

  kotlintestslinux:
    if: ${{ needs.env.outputs.mobile_android_tests == 'true' }}
    needs: env
    permissions:
      contents: read
      packages: read
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ${{ needs.env.outputs.agent_ubuntu }}
    timeout-minutes: 90
    container:
      image: ${{ needs.env.outputs.build_image_ubuntu_mobile }}
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v4
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run Kotlin library integration tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile
        ./bazelw test \
            --build_tests_only \
            --config=test-android \
            --config=mobile-remote-ci \
            --define=signal_trace=disabled \
            //test/kotlin/...
