name: mobile_asan

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/env.yml
    secrets: inherit

  asan:
    if: ${{ needs.env.outputs.asan == 'true' }}
    needs: env
    name: asan
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-818d28832abf2a7c0cb2bff00435be231729a0bf
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-asan") \
            //test/common/...
