on:
  schedule:
    - cron: '0 8 * * 1,2,3,4,5'

jobs:
  pr_notifier:
    name: PR Notifier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/actions/pr_notifier/requirements.txt
      - name: Display Python version
        run: python ./.github/actions/pr_notifier/pr_notifier.py
