name: test
on:
  workflow_dispatch:
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: explore
        shell: bash
        run: |
         sudo cat /proc/cpuinfo
         sudo apt-get update --error-on=any
         sudo apt-get install --yes libtool cmake automake autoconf make ninja-build curl unzip virtualenv openjdk-11-jdk build-essential libc++1
